nilfs-utils: fix coding style issues: space required before the open parenthesis
This fixes the following coding style issues:

 ERROR: space required before the open parenthesis '('
 #154: FILE: sbin/mount/sundries.c:154:
 +     while(1) {

 ERROR: space required before the open parenthesis '('
 #45: FILE: sbin/mount/mount_mntent.c:45:
 +       while(1) {

 ERROR: space required before the open parenthesis '('
 #92: FILE: sbin/mount/mount_mntent.c:92:
 +       while(s != ss) {

 ERROR: space required before the open parenthesis '('
 #211: FILE: sbin/mount/mount_mntent.c:211:
 +               while(isdigit(*s)) s++;

 ERROR: space required before the open parenthesis '('
 #214: FILE: sbin/mount/mount_mntent.c:214:
 +       if(*s && !is_space_or_tab(*s))

 ERROR: space required before the open parenthesis '('
 #218: FILE: sbin/mount/mount_mntent.c:218:
 +       if(isdigit(*s)) {

 ERROR: space required before the open parenthesis '('
 #220: FILE: sbin/mount/mount_mntent.c:220:
 +               while(isdigit(*s)) s++;

 ERROR: space required before the open parenthesis '('
 #223: FILE: sbin/mount/mount_mntent.c:223:
 +       if(*s && !is_space_or_tab(*s))

Signed-off-by: Ryusuke Konishi <konishi.ryusuke@lab.ntt.co.jp>