nilfs-utils: add missing space chars
Fix the following checkpatch errors:

 ERROR: spaces required around that '==' (ctx:VxV)
 #219: FILE: mount/mount_opts.c:219:
 +       if (optdata==NULL || *optdata=='\0' || optname==NULL)
                    ^

 ERROR: spaces required around that '==' (ctx:VxV)
 #219: FILE: mount/mount_opts.c:219:
 +       if (optdata==NULL || *optdata=='\0' || optname==NULL)
                                      ^

 ERROR: spaces required around that '==' (ctx:VxV)
 #219: FILE: mount/mount_opts.c:219:
 +       if (optdata==NULL || *optdata=='\0' || optname==NULL)
                                                       ^

 ERROR: spaces required around that '==' (ctx:WxV)
 #223: FILE: mount/mount_opts.c:223:
 +       data = *optdata =='"' ? strip_quotes(optdata) : optdata;
                         ^

 ERROR: spaces required around that '=' (ctx:VxV)
 #328: FILE: mount/mount_opts.c:328:
 +               for (p=opts, opt=NULL; p && *p; p++) {
                       ^

 ERROR: spaces required around that '=' (ctx:VxV)
 #328: FILE: mount/mount_opts.c:328:
 +               for (p=opts, opt=NULL; p && *p; p++) {
                                 ^
 ...

Signed-off-by: Ryusuke Konishi <konishi.ryusuke@lab.ntt.co.jp>