nilfs-resize: fix abnormal minimum size error output for sizes less than 4KiB
If we specify a device size less than 4096 bytes, an insufficient size
error will occur, but due to an underflow in calculating the number of
segments, the output of the required number of segments and required
size will become abnormal:

 $ sudo nilfs-resize /dev/loop0 1024
 Partition size = 8796093023232 bytes.
 Shrink the filesystem size from 8796093022720 bytes to 1024 bytes.
 Error: the filesystem does not have enough free space.
        At least 18446741984637458845 more segments (922337203713998848
 bytes) are required.
 Aborted.

Fix this issue by preventing underflow when calculating the number of
segments.

Signed-off-by: Ryusuke Konishi <konishi.ryusuke@gmail.com>