mkfs.nilfs2: fix wrong suggestion of minimum device size
Even if we give "required size" that mkfs.nilfs2 suggests for too
small devices, mkfs.nilfs2 fails due to the lack of consideration of
the trailing super block:

 Error: too small device.
        device size=134217728 bytes, required size=134217728 bytes.
        Please enlarge the device, or shorten segments with -B option.

This fixes the issue.

Signed-off-by: Ryusuke Konishi <konishi.ryusuke@gmail.com>