nilfs-utils: remove trailing whitespaces
This fixes trailing whitespace issues as follows which are reported by
checkpatch script:

ERROR: trailing whitespace
+^I^I$

Signed-off-by: Ryusuke Konishi <konishi.ryusuke@lab.ntt.co.jp>