libcnormap: use unsigned int for one-bit bitfields
The one-bit bitfields in 'struct nilfs_cnormap' are currently defined
as 'int'.  On two's complement systems, a one-bit signed integer can
only represent 0 and -1, which is not suitable for boolean flags
intended to hold 0 or 1.

Change them to 'unsigned int' to ensure they can represent 0 and 1
correctly.

While at it, clean up the comments for these members to improve
readability.

This resolves the following Sparse errors reported:

cnormap.c:64:35: error: dubious one-bit signed bitfield
cnormap.c:69:42: error: dubious one-bit signed bitfield
cnormap.c:70:43: error: dubious one-bit signed bitfield

Signed-off-by: Ryusuke Konishi <konishi.ryusuke@gmail.com>