nilfs-utils: fix coding style issues: space required after that ','
This fixes the following coding style issues:

 ERROR: space required after that ',' (ctx:VxV)
 #51: FILE: bin/lssu.c:51:
 +       {"index",required_argument, NULL, 'i'},
                 ^
 ERROR: space required after that ',' (ctx:VxV)
 #52: FILE: bin/lssu.c:52:
 +       {"lines",required_argument, NULL, 'n'},
                 ^
 ERROR: space required after that ',' (ctx:VxV)
 #88: FILE: sbin/mkfs/mkfs.c:88:
 +#define ROUNDUP_DIV(n,m)   (((n) - 1) / (m) + 1)
                       ^
 ERROR: space required after that ',' (ctx:VxV)
 #89: FILE: sbin/mkfs/mkfs.c:89:
 +#define max_t(type,x,y) \
                   ^
 ERROR: space required after that ',' (ctx:VxV)
 #89: FILE: sbin/mkfs/mkfs.c:89:
 +#define max_t(type,x,y) \
                      ^
 ERROR: space required after that ',' (ctx:VxV)
 #307: FILE: sbin/mkfs/mkfs.c:307:
 +#define BLKDISCARD     _IO(0x12,119)
                                ^
 ERROR: space required after that ',' (ctx:VxV)
 #311: FILE: sbin/mkfs/mkfs.c:311:
 +#define BLKDISCARDZEROES _IO(0x12,124)
                                  ^
 ERROR: space required after that ',' (ctx:VxV)
 #19: FILE: sbin/mkfs/bitops.c:19:
 +int ext2fs_set_bit(int nr,void * addr)
                          ^
 ERROR: space required after that ',' (ctx:VxV)
 #55: FILE: sbin/mkfs/mkfs.h:55:
 +extern int ext2fs_set_bit(int nr,void * addr);
                                  ^
 ...

Signed-off-by: Ryusuke Konishi <konishi.ryusuke@lab.ntt.co.jp>